BitCounter/Models/CounterModel.cs
using System.Collections.Generic;

namespace BitCounter.Models
{
    public class CounterModel
    {
        public string ByteString;

        public CounterModel()
        { }

        public CounterModel(string byteString, List<int> countersList)
        {
            this.ByteString = byteString;
            this.Counter1 = countersList[0];
            this.Counter2 = countersList[1];
            this.Counter3 = countersList[2];
            this.Counter4 = countersList[3];
            this.Counter5 = countersList[4];
            this.Counter6 = countersList[5];
            this.Counter7 = countersList[6];
            this.Counter8 = countersList[7];
        }

        public int Counter1 { get; set; }
        public int Counter2 { get; set; }
        public int Counter3 { get; set; }
        public int Counter4 { get; set; }
        public int Counter5 { get; set; }
        public int Counter6 { get; set; }
        public int Counter7 { get; set; }
        public int Counter8 { get; set; }
    }
}

BitCounter/Models/ErrorViewModel.cs
namespace BitCounter.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BitCounter/Models/SaveSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BitCounter.Models
{
    public class SaveSettings
    {
        public string SavePeriod { get; set; }
        public string SaveFolder { get; set; }
    }
}

BitCounter/Controllers/ApiController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BitCounter.Models;
using BitCounter.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

namespace BitCounter.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class ApiController : ControllerBase
    {
        private readonly IHostedService counterService;
        private readonly IDataProviderService dataProviderService;
        private readonly SaveSettings saveSettings;

        public ApiController(
            IHostedService counterService,
            IDataProviderService dataProviderService,
            IOptions<SaveSettings> settings)
        {
            this.counterService = counterService;
            this.dataProviderService = dataProviderService;
            this.saveSettings = settings.Value;
        }

        [HttpGet("[action]")]
        public async Task<IActionResult> StartCounter()
        {
            await counterService.StartAsync(new CancellationToken(false));
            return Ok("Counter Service Started");
        }

        [HttpGet("[action]")]
        public async Task<IActionResult> StopCounter()
        {
            await counterService.StopAsync(new CancellationToken(true));
            return Ok("Counter Service Stopped");
        }

        [HttpGet("[action]")]
        public IActionResult ShowData()
        {
            var result = dataProviderService.GetCounterDataFromFolder(saveSettings.SaveFolder).TakeLast(10);
            return Ok(result);
        }
    }
}

BitCounter/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BitCounter.Models;

namespace BitCounter.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BitCounter/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="col-md-12">
    <a class="btn btn-default" asp-controller="Api" asp-action="StartCounter">Start Counter</a>
    <a class="btn btn-default" asp-controller="Api" asp-action="StopCounter">Stop Counter</a>
    <a class="btn btn-default" asp-controller="Api" asp-action="ShowData" asp-route-date="04/27/1991">Show Data</a>
</div>

BitCounter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BitCounter</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header col-md-12">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">BitCounter</a>
        </div>
    </nav>


    <div class="body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>